# https://taskfile.dev

version: '3'

tasks:
  default:
    - task: update
    - task: fmt
    - task: build
    - task: lint
    - task: check

  wasm:
    - gogio -target js -ldflags="-s -w" -o wasm_assets github.com/v0vc/go-music-grpc

  fmt:
    - goimports -w -l .
    - gofumpt -w -l .

  lint:
    - go vet ./...
    - staticcheck ./...
    - nilaway ./...

  update:
    - go get gioui.org@latest
    - go get -u all
    - go mod tidy

  build:
    - go build -ldflags="-s -w" ./server
    - go build -ldflags="-s -w" ./gio-gui

  check:
    - govulncheck ./...